name: Auto Update PutoTV
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: install dependencies
        run: npm install
      - name: Create m3u xml
        run: node ./index.js --exclude-groups "Español"
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add plutotv_us.xml plutotv_us.m3u8
          git commit -m "Auto Update PlutoTV"
          git push



