name: Auto Update PutoTV
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: './package-lock.json'
      - name: install dependencies
        run: npm install
      - name: Create m3u xml
        run: node ./index.js 
      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add pl.guide.xml pl.guide.xml.gz
          git commit -m "Auto Update PL EPG"
          git push
